name: workflow context

on:
    push:
        branches:
            - main

jobs:
    my_job:
        runs-on: ubuntu-latest
        env:
          my_work_name: ${{ github.action}}
        steps:
          - name: Print the workflow name through context
            run: echo "The workflow I am running is ${{my_work_name}}"

