name: workflow-dispatch
on:
  workflow_dispatch:
    inputs:
      name:
        description: "Enter your name"
        required: true

jobs:
  greetings:
    runs-on: ubuntu-latest
    steps:
      - name: Greet
        run: echo "Hello ${{github.event.inputs.name}}. Good day !!"     
        