name: multi-event

on:
    workflow_dispatch:
        inputs:
            Env:
                description: Mention the Env
                required: true
          
            name:
              description: Enter your name
              required: true

    push:
        branches:
            - test
            - dev

jobs:
  myJob:
    runs-on: ubuntu-latest
    steps:
      - name: Just print something
        run: echo "Branch getting triggered is ${{ github.ref_name }}"
           
        