name: multi-event

on:
    push:
        branches:
            - test
            - dev

jobs:
  myJob:
    runs-on: ubuntu-latest
    steps:
      - name: Just print something
        run: echo "Branch getting triggered is ${{ github.ref_name }}"
           
        