name: "Webhook Event example"

on:
  repository_dispatch:
    types:
      - webhook

jobs:
  respond-to-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Print the event type
        run: echo "Event of type $GITHUB_EVENT_NAME"

      - name: Print the payload message
        run: echo "The message is ${{ github.event.client_payload.whatsmahname }}"


        